# This will run on Travis' 'new' container-based infrastructure
sudo: true

# Setup for Ubuntu Bionic (18.04)
dist: focal

language:
  - python

addons:
  apt:
    packages:
      - python3-dev
      - python3-pip

python:
  - 3.8

git:
  clone: false

# Environment variables
env:
  global:
    - GH_REPO_URL: github.com/slaclab/ucsc-hn
    - PACKAGE_DIR: $HOME/packages
    - MINICONDA_DIR: $PACKAGE_DIR/miniconda
    - DOWNLOAD_DIR: ${HOME}/download
    - DOWNLOAD_URL: ${GH_REPO_URL}/releases/download/${TRAVIS_TAG}/rogue_${TRAVIS_TAG}.zip

stages:
    - name: deploy_tag
      if: tag IS present

# Generate and deploy documentation
jobs:
  include:
    - &deploy-conda-stage       # Conda for linux
      stage: deploy_tag
      name: "Deploy Conda"
      before_install:
        # Prepare folders
        - mkdir -p $MINICONDA_DIR
        - mkdir -p $DOWNLOAD_DIR

      install:
        # Install Anaconda for the right architecture (linux or osx)
        - cd $MINICONDA_DIR
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh;
          else
            wget -O miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh;
          fi
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - source "$HOME"/miniconda/etc/profile.d/conda.sh
        - conda config --set always_yes yes
        - conda install conda-build anaconda-client conda-verify
        - conda update -q conda conda-build
        # Download and unzip tag zipfile
        - cd $DOWNLOAD_DIR
        - wget -O file.zip $DOWNLOAD_URL
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
            7za x file.zip;
          else
            unzip file.zip;
          fi

      script:
        # Build conda package
        - travis_wait 60 conda build --debug conda-recipe --output-folder bld-dir -c tidair-tag -c tidair-packages -c conda-forge

      after_success:
        # Upload conda package
        - anaconda -t $CONDA_UPLOAD_TOKEN_TAG upload bld-dir/`echo $TRAVIS_OS_NAME`-64/*.tar.bz2

